export * from "./Header";
export * from "./Footer";
export * from "./About";
export * from "./App";
export * from "./Background/background";
export * from "./Main/Main";
export * from "./Pages/Company";
export * from "./Pages/Resources";
export * from "./Pages/Services";
export * from "./Pages/Solution";
export * from "./Forms/Forms";
// export * from "./Map";
